Repository atlp-rwanda/phatom-be-techode, pull requests merged in 2022-04, with the labels that each got.

#6 Ch setup continious integration tp 18
  .codeclimate.yml
  .coveralls.yml
  .github/workflows/develop.yml
  .gitignore
  README.md
  app.js
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/phatom-be-techode/app.js.html
  coverage/lcov-report/phatom-be-techode/controllers/index.html
  coverage/lcov-report/phatom-be-techode/controllers/userController.js.html
  coverage/lcov-report/phatom-be-techode/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/users.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package-lock.json
  package.json
  routes/users/users.js
  test/app.test.js
Labels: Done

#7 #TP-19 ch(docker): docker setup
  .dockerignore
  Dockerfile
  docker-compose.yml
  package-lock.json
Labels: Done

#3 #TP-17 ch(set up Postgres) Configure the app to use Postgres database
  .DS_Store
  .babelrc
  .github/workflows/develop.yml
  .gitignore
  .seqluelizerc
  app.js
  config/config.js
  config/options.js
  controllers/userController.js
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/phatom-be-techode/app.js.html
  coverage/lcov-report/phatom-be-techode/controllers/index.html
  coverage/lcov-report/phatom-be-techode/controllers/userController.js.html
  coverage/lcov-report/phatom-be-techode/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/users.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  function/respond.js
  locales/en/translation.json
  locales/fr/translation.json
  migrations/20220404113821-create-users.js
  migrations/20220404151621-create-roles.js
  migrations/20220404151806-create-roles.js
  migrations/20220404152139-create-buses.js
  models/buses.js
  models/index.js
  models/roles.js
  models/users.js
  package-lock.json
  package.json
  routes/language.js
  routes/users/users.js
  seeders/20220404151054-users.js
  test/app.test.js
  test/language.test.js
  test/user.test.js
  user.json
Labels: Done

#14 #TP-8 ft:Sign in to Phantom
  .github/workflows/develop.yml
  README.md
  app.js
  config/options.js
  controllers/authController.js
  controllers/authsController.js
  controllers/userController.js
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/phatom-be-techode/app.js.html
  coverage/lcov-report/phatom-be-techode/controllers/index.html
  coverage/lcov-report/phatom-be-techode/controllers/userController.js.html
  coverage/lcov-report/phatom-be-techode/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/users.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  function/respond.js
  locales/en/translation.json
  locales/fr/translation.json
  middleware/auth.js
  middleware/validation.js
  migrations/20220404113821-create-users.js
  models/users.js
  package-lock.json
  package.json
  routes/logins.js
  seeders/20220404151054-users.js
  test/app.test.js
  test/signin.test.js
Labels: Need review

#16 bg(fixing) fixing coveralls
  controllers/driversController.js
  controllers/operatorsController.js
  controllers/rolesController.js
  coverage/lcov-report/index.html
  coverage/lcov-report/phatom-be-techode/app.js.html
  coverage/lcov-report/phatom-be-techode/controllers/index.html
  coverage/lcov-report/phatom-be-techode/controllers/userController.js.html
  coverage/lcov-report/phatom-be-techode/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/index.html
  coverage/lcov-report/phatom-be-techode/routes/users/users.js.html
  coverage/lcov.info
Labels: bug, Done

#20 #TP-11 ft: create, delete, update and read for buses
  .codeclimate.yml
  app.js
  controllers/busesController.js
  controllers/driversController.js
  controllers/operatorsController.js
  controllers/permissionsController.js
  controllers/rolesController.js
  controllers/userController.js
  function/respond.js
  function/validation.js
  locales/en/translation.json
  locales/fr/translation.json
  middlewares/auth.js
  middlewares/checkAuthorization.js
  middlewares/isValidaId.js
  middlewares/permssionRoleExist.js
  migrations/20220404152139-create-buses.js
  migrations/20220414130159-create-buses.js
  models/buses.js
  package.json
  routes/buses/busesRoute.js
  routes/drivers/driversRoute.js
  routes/operators/operatorsRoute.js
  routes/permissions/permissions.js
  routes/roles/roles.js
  seeders/20220416134717-buses.js
  test/bus.test.js
  test/driver.test.js
  test/operator.test.js
  test/role.test.js
  test/signin.test.js
  utils/paginate.js
Labels: Need review

#19 #TP-22 ft:(resetPasword) forgot password and reset password
  .codeclimate.yml
  .github/workflows/develop.yml
  app.js
  config/config.js
  config/options.js
  controllers/authController.js
  controllers/driversController.js
  controllers/operatorsController.js
  controllers/resetController.js
  function/respond.js
  locales/en/translation.json
  locales/fr/translation.json
  migrations/20220410174911-create-reset-token.js
  models/index.js
  models/resetTokens.js
  package-lock.json
  package.json
  routes/users/accounts.js
  routes/users/users.js
  test/driver.test.js
  test/language.test.js
  test/resetPassword.test.js
  test/role.test.js
  test/user.test.js
  utils/renderMail.js
  utils/resetUtil.js
  utils/sendEmail.js
Labels: Need review

#23 #TP-7 ft(crudRoute): CRUD operation for route
  app.js
  controllers/driversController.js
  controllers/operatorsController.js
  controllers/rolesController.js
  controllers/routesController.js
  function/validation.js
  locales/en/translation.json
  locales/fr/translation.json
  middlewares/validateRouteEntry.js
  migrations/20220419071816-create-route.js
  models/route.js
  package-lock.json
  package.json
  routes/routes/routesRoute.js
  test/driver.test.js
  test/operator.test.js
  test/resetPassword.test.js
  test/route.test.js
Labels: Need review

#22 #TP-38 ft:update-profile
  .DS_Store
  app.js
  controllers/authsController.js
  controllers/profileContoller.js
  controllers/userController.js
  function/validation.js
  locales/.DS_Store
  locales/en/translation.json
  locales/fr/translation.json
  middlewares/checkAuthorization.js
  migrations/20220422073225-update_profile.js
  models/users.js
  package-lock.json
  routes/profile/profilePic.js
  test/bus.test.js
  test/profile.test.js
  test/user.test.js
  utils/resetUtil.js
Labels: Need review

#21 #TP-12 ft(assign) assign drivers buses
  app.js
  controllers/assignBusController.js
  controllers/authController.js
  controllers/authsController.js
  controllers/dammyController.js
  controllers/dashboardController.js
  controllers/driversController.js
  controllers/operatorsController.js
  controllers/profileContoller.js
  controllers/resetController.js
  controllers/userController.js
  function/respond.js
  function/validation.js
  locales/en/translation.json
  locales/fr/translation.json
  middlewares/paginate.js
  middlewares/validation.js
  migrations/20220415180939-add-columns-to-users.js
  migrations/20220420065343-create-drivers.js
  migrations/20220420065353-create-operators.js
  migrations/20220420073326-driver-to-user-association.js
  migrations/20220420073349-operator-to-user-association.js
  migrations/20220420073406-driver-to-bus-association.js
  models/drivers.js
  models/index.js
  models/operators.js
  models/users.js
  routes/buses/busesRoute.js
  routes/dashboard/dashboard.js
  routes/drivers/driversRoute.js
  routes/operators/operatorsRoute.js
  routes/users/users.js
  seeders/20220404151054-users.js
  seeders/20220416134717-buses.js
  seeders/20220420170042-drivers.js
  seeders/20220420170235-operators.js
  test/bus.test.js
  test/driver.test.js
  test/language.test.js
  test/operator.test.js
  test/paginate.test.js
  test/profile.test.js
  test/resetPassword.test.js
  test/role.test.js
  test/route.test.js
  test/signin.test.js
  test/user.test.js
  utils/renderMail.js
  utils/resetUtil.js
  utils/testData.js
Labels: Need review
